

<div class="container text-center content-wrapper">
    <h1 class="bg-danger text-white">BUSINESS DEPARTMENT</h1>

    <div class="row">
        <div class="col-md-4">
            <h3 class="font-weight-bold">Number of Live Bids</h3>
            <p class="display-4">4,000,000</p>
        </div>

        <div class="col-md-4">
            <h3 class="font-weight-bold">Total Bids</h3>
            <p class="display-4">5,000,000</p>
        </div>

        <div class="col-md-4">
            <h3 class="font-weight-bold">Number of Current Leads</h3>
            <p class="display-4">2000</p>
        </div>
    </div>
</div>
