

<div class="container-fluid text-center">
    <h1 class="mb-4">HEALTH & SAFETY DEPARTMENT</h1>

    <div class="row">
        <div class="col-md-4">
            <h3 class="font-weight-bold">Total Accidents</h3>
            <p class="display-4">40</p>
        </div>

        <div class="col-md-4">
            <h3 class="font-weight-bold">Health and Safety Bulletin</h3>
            <p class="display-4 text-warning">Pending</p>
        </div>

        <div class="col-md-4">
            <h3 class="font-weight-bold">Absences</h3>
            <p class="display-4">30</p>
        </div>
    </div>
</div>
