<!DOCTYPE html>
<html lang="en">

<head>
    <title>Morson Group</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta content="text/html; charset=iso-8859-2" http-equiv="Content-Type">
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        .mySlides {
            display: none;
        }
        body {
            /* Set the background image and specify its dimensions */
            background-image: url('images/business1.jpg');
            background-size: cover;
            background-attachment: fixed;
            /* Set the width and height of the background image container */
            width: 100vw;
            height: 100vh;
            margin: 0; /* Remove default body margin */
            padding: 0; /* Remove default body padding */
        }
    </style>
</head>

<body>

<div class="container text-white">
    <h2 class="text-center mt-3">MORSON PROJECTS</h2>

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <p><?php require("header.phtml"); ?></p>
        <div class="carousel-inner">

            <?php
            $slides = [
                'business.php',
                'healthAndSafety.php',
                'itSystem.php',
                'commercial.php',
                'hr.php'
            ];

            $firstSlide = true;
            foreach ($slides as $index => $slide) {
                echo '<div class="carousel-item ';
                echo $firstSlide ? 'active' : '';
                echo '">';
                echo '<p>';
                require($slide);
                echo '</p>';
                echo '</div>';
                $firstSlide = false;
            }
            ?>

        </div>
        <p><?php require("footer.phtml"); ?></p>
<!---->
<!--        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">-->
<!--            <span class="carousel-control-prev-icon" aria-hidden="true"></span>-->
<!--            <span class="sr-only">Previous</span>-->
<!--        </a>-->
<!--        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">-->
<!--            <span class="carousel-control-next-icon" aria-hidden="true"></span>-->
<!--            <span class="sr-only">Next</span>-->
<!--        </a>-->
    </div>
</div>

<!-- Include Bootstrap JS and jQuery -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

<script>
    var myIndex = 0;
    carousel();

    function carousel() {
        var i;
        var x = document.getElementsByClassName("carousel-item");
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";
        }
        myIndex++;
        if (myIndex > x.length) {
            myIndex = 1
        }
        x[myIndex - 1].style.display = "block";
        setTimeout(carousel, 10000); // Change slide every 30 seconds
    }
</script>

</body>

</html>
