    <div class="container text-center content-wrapper">
        <h1 class="bg-danger text-white">BUSINESS DEPARTMENT</h1>

            <?php foreach ($view->departmentDataSet as $business): ?>
        <div class="row">
                <div class="col-md-4">
                    <h3 class="font-weight-bold">Month</h3>
                    <?php
                    try {
                        $date = new DateTime($business->getMonth());
                        $formattedMonth = $date->format('F');
                        echo '<p class="display-4 text-primary">' . $formattedMonth . '</p>';
                    } catch (Exception $e) {
                        echo '<p class="display-4 text-danger">Month not found</p>';
                    }
                    ?>
                </div><br>
                <div class="col-md-4">
                    <h3 class="font-weight-bold">Live Bids</h3>
                        <?php echo '<p class="display-4 text-primary">' . $business->getLiveBids() . '</p>'; ?>
                </div>
        </div>
            <br><br>
        <div class="row">
                <div class="col-md-4">
                    <h3 class="font-weight-bold">Total Bids</h3>
                        <?php echo '<p class="display-4 text-primary">' . $business->getBidTotal() . '</p>'; ?>
                </div>
                 <br>
                <div class="col-md-4">
                    <h3 class="font-weight-bold">Current Leads</h3>
                        <?php echo '<p class="display-4 text-primary">' . $business->getLeads() . '</p>'; ?>
                </div>
        </div>
            <?php endforeach; ?>

    </div>
