
<div class="container text-center">
    <h1 class="display-4 text-center">COMMERCIAL DEPARTMENT</h1>

    <div class="row">
        <div class="col-md-4">
            <h3 class="font-weight-bold">What is Payday?</h3>
            <p class="lead">Happy Friday, Every Friday is Payday</p>
        </div>

        <div class="col-md-4">
            <h3 class="font-weight-bold">Payroll Bulletins</h3>
            <p class="display-4 text-warning">Pending</p>
        </div>

        <div class="col-md-4">
            <h3 class="font-weight-bold">Best Performing Projects</h3>
            <p class="display-4">Website Production</p>
        </div>
    </div>
</div>
