

<div class="container-fluid text-center">
    <h1 class="mb-4">HEALTH & SAFETY DEPARTMENT</h1>

    <div class="row">
        <?php foreach ($view->healthAndSafety as $dataSet): ?>
        <div class="col-md-3">
            <h3 class="font-weight-bold">Month</h3>
            <p class="display-3">
                <?php
                try {
                    $date = new DateTime($dataSet->getMonth());
                    $formattedMonth = $date->format('F');
                    echo '<p class="display-4 text-primary">' . $formattedMonth . '</p>';
                } catch (Exception $e) {
                    echo '<p class="display-4 text-danger">Month not found</p>';
                }
                ?>
            </p>
        </div>
        <div class="col-md-3">
            <h3 class="font-weight-bold">Total Accidents</h3>
            <?php echo '<p class="display-4 text-primary">' . $dataSet->getTotalAccidents() . '</p>'; ?>
        </div>

        <div class="col-md-3">
            <h3 class="font-weight-bold">Health and Safety Bulletin</h3>
            <?php echo '<p class="display-5 text-primary">' . $dataSet->getBulletin() . '</p>'; ?>

        </div>

        <div class="col-md-3">
            <h3 class="font-weight-bold">Absences</h3>
            <?php echo '<p class="display-4 text-primary">' . $dataSet->getAbsences() . '</p>'; ?>
        </div>
        <?php endforeach; ?>
    </div>
</div>
