<!-- hr.phtml -->
<div class="container text-center">
    <h1 class="bg-info text-center">HUMAN & RESOURCE DEPARTMENT</h1>

    <div class="row">
        <div class="col-md-4">
            <h3 class="font-weight-bold">HR Bulletin</h3>
            <p class="display-4">60</p>
        </div>

        <div class="col-md-4">
            <h3 class="font-weight-bold">Upcoming Bank Holidays</h3>
            <p class="display-4">2nd of February 2024</p>
        </div>

        <div class="col-md-4">
            <h3 class="font-weight-bold">Benefits Announcement</h3>
            <p class="display-4 text-warning">Pending</p>
        </div>
    </div>
</div>
