<!-- hr.phtml -->
<div class="container text-center">
    <h1 class="bg-info text-center">HUMAN & RESOURCE DEPARTMENT</h1>
    <?php foreach ($view->humanResource as $hr): ?>
    <div class="row">
        <div class="col-md-3">
            <h3 class="font-weight-bold">Month</h3>
            <?php
            try {
                $date = new DateTime($hr->getMonth());
                $formattedMonth = $date->format('F');
                echo '<p class="display-3 text-primary">' . $formattedMonth . '</p>';
            } catch (Exception $e) {
                echo '<p class="display-3 text-danger">Month not found</p>';
            }
            ?>
        </div>
        <div class="col-md-4">
            <h3 class="font-weight-bold">HR Bulletin</h3>
            <?php echo '<p class=" text-primary">' .$hr->getHrBulletin(). '</p>'; ?>
        </div>
        <div class="col-md-4">
            <h3 class="font-weight-bold">Upcoming Bank Holidays</h3>
            <?php echo '<p class="text-primary">' . $hr->getBankHoliday(). '</p>'; ?>
        </div>

        <div class="col-md-4">
            <h3 class="font-weight-bold">Benefits Announcement</h3>
            <?php echo '<p class="text-primary">' . $hr->getAnnouncement(). '</p>'; ?>
        </div>
    </div>
    <?php endforeach;?>
</div>
